<?php

namespace api\controllers;

use yii\filters\auth\HttpHeaderAuth;
use yii\rest\ActiveController;


class ApiBaseController extends ActiveController
{
    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'],$actions['update'],$actions['create'],$actions['delete'],$actions['vies']);
    }

    /*    public function behaviors()
        {
            $behaviors = parent::behaviors();
            $behaviors['authenticator'] = [
                'class' => HttpHeaderAuth::className(),
            ];
            return $behaviors;
        }*/
}
